mutt - Check if in mutt source dir before config

diff --git a/mutt/configure b/mutt/configure
--- a/mutt/configure
+++ b/mutt/configure
@@ -1,3 +1,10 @@
+#!/bin/sh
+
+if ! [ -f muttlib.c ]; then
+  echo "muttlib.c not found, are you in a mutt source directory?" >&2
+  exit 1
+fi
+
 export CFLAGS=-ggdb
 exec ./prepare \
 	--sysconfdir=/etc \
